
services:
  app:
    image: bluediamond-backend:local
    container_name: bluediamond-backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: bluediamond-database
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: bluediamond
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
    volumes:
      - db-data:/var/lib/mysql
  
volumes:
  db-data: